 package com.alex.jpa.data;

// default package
// Generated May 16, 2016 12:49:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "test")
public class Users implements java.io.Serializable {

	private String username;
	private String name;
	private String surname;
	private String address;
	private String password;

	public Users() {
	}

	public Users(String username) {
		this.username = username;
	}

	public Users(String username, String name, String surname, String address, String password) {
		this.username = username;
		this.name = name;
		this.surname = surname;
		this.address = address;
		this.password = password;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", length = 20)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "address", length = 20)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "password", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
